version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/all_messages/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=all_messages
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=all_messages

volumes:
  postgres_data: